create schema if not exists oak_internal;
revoke all on schema oak_internal from public, anon, authenticated;
grant usage on schema oak_internal to service_role;
create table oak_internal.push_keys (id boolean primary key default true check(id), keys jsonb not null);
grant select,insert on oak_internal.push_keys to service_role;
create function public.oak_push_keys() returns jsonb language sql security invoker set search_path='' as $$ select keys from oak_internal.push_keys where id=true $$;
revoke all on function public.oak_push_keys() from public,anon,authenticated;
grant execute on function public.oak_push_keys() to service_role;
create table public.oak_push_subscriptions (endpoint text primary key, user_id uuid not null references public.oak_operators(user_id) on delete cascade, subscription jsonb not null, created_at timestamptz default now(), last_test timestamptz);
alter table public.oak_push_subscriptions enable row level security;
revoke all on public.oak_push_subscriptions from anon,authenticated;
create table public.oak_push_events (request_id uuid primary key references public.oak_requests(id) on delete cascade, status text not null default 'pending', attempts integer not null default 0, claimed_at timestamptz, delivered jsonb not null default '[]');
alter table public.oak_push_events enable row level security;
revoke all on public.oak_push_events from anon,authenticated;
grant all on public.oak_push_events,public.oak_push_subscriptions to service_role;
create function public.oak_queue_push() returns trigger language plpgsql security definer set search_path='' as $$ begin if new.ready and not old.ready then insert into public.oak_push_events(request_id) values(new.id) on conflict do nothing; end if; return new; end $$;
revoke all on function public.oak_queue_push() from public,anon,authenticated;
create trigger oak_request_push after update of ready on public.oak_requests for each row execute function public.oak_queue_push();
create function public.oak_claim_push() returns setof public.oak_push_events language sql security invoker set search_path='' as $$ update public.oak_push_events set status='processing',claimed_at=now(),attempts=attempts+1 where request_id in (select request_id from public.oak_push_events where (status='pending' or (status='processing' and claimed_at<now()-interval '3 minutes')) and attempts<5 order by request_id limit 10 for update skip locked) returning * $$;
revoke all on function public.oak_claim_push() from public,anon,authenticated;
grant execute on function public.oak_claim_push() to service_role;
